name: don_icons
description: A new flutter plugin project.
version: 0.0.1
author: donfo <aspzjfa@foxmail.com>
homepage: https://github.com/donfo/don_icons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Iconfont
      fonts:
        - asset: lib/fonts/iconfont.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
