library don_icons;

import 'package:flutter/widgets.dart';

class IconDataDon extends IconData {
  const IconDataDon(int codePoint)
      : super(codePoint, fontFamily: 'Iconfont', fontPackage: 'don_icons');
}

// THIS FILE IS AUTOMATICALLY GENERATED!

class DonIcons {
  static const IconData loading1 = const IconDataDon(0xe71d);
  static const IconData loading5 = const IconDataDon(0xe6da);
  static const IconData loading2 = const IconDataDon(0xe6db);
  static const IconData sync = const IconDataDon(0xe786);
  static const IconData loading = const IconDataDon(0xe6dd);
  static const IconData loading3 = const IconDataDon(0xe6de);
  static const IconData loading4 = const IconDataDon(0xe6df);
  static const IconData birthday_cake_o = const IconDataDon(0xe620);
  static const IconData calender_o = const IconDataDon(0xe621);
  static const IconData cash_on_deliver = const IconDataDon(0xe622);
  static const IconData chat = const IconDataDon(0xe623);
  static const IconData cart_o = const IconDataDon(0xe624);
  static const IconData cart_circle_o = const IconDataDon(0xe625);
  static const IconData chat_o = const IconDataDon(0xe626);
  static const IconData cart_circle = const IconDataDon(0xe627);
  static const IconData clock_o = const IconDataDon(0xe628);
  static const IconData certificate = const IconDataDon(0xe629);
  static const IconData bulb_o = const IconDataDon(0xe62a);
  static const IconData cluster = const IconDataDon(0xe62b);
  static const IconData clear = const IconDataDon(0xe62c);
  static const IconData card = const IconDataDon(0xe62d);
  static const IconData column = const IconDataDon(0xe62e);
  static const IconData circle = const IconDataDon(0xe62f);
  static const IconData browsing_history = const IconDataDon(0xe630);
  static const IconData close = const IconDataDon(0xe631);
  static const IconData cluster_o = const IconDataDon(0xe632);
  static const IconData cash_back_record = const IconDataDon(0xe633);
  static const IconData checked = const IconDataDon(0xe634);
  static const IconData comment_o = const IconDataDon(0xe635);
  static const IconData completed = const IconDataDon(0xe636);
  static const IconData coupon_o = const IconDataDon(0xe637);
  static const IconData clock = const IconDataDon(0xe638);
  static const IconData comment_circle_o = const IconDataDon(0xe639);
  static const IconData cashier_o = const IconDataDon(0xe63a);
  static const IconData contact = const IconDataDon(0xe63b);
  static const IconData comment = const IconDataDon(0xe63c);
  static const IconData desktop_o = const IconDataDon(0xe63d);
  static const IconData debit_pay = const IconDataDon(0xe63e);
  static const IconData diamond_o = const IconDataDon(0xe63f);
  static const IconData chart_trending_o = const IconDataDon(0xe640);
  static const IconData exchange = const IconDataDon(0xe641);
  static const IconData failure = const IconDataDon(0xe642);
  static const IconData closed_eye = const IconDataDon(0xe643);
  static const IconData cross = const IconDataDon(0xe644);
  static const IconData coupon = const IconDataDon(0xe645);
  static const IconData edit = const IconDataDon(0xe646);
  static const IconData fail = const IconDataDon(0xe647);
  static const IconData envelop_o = const IconDataDon(0xe648);
  static const IconData descending = const IconDataDon(0xe649);
  static const IconData eye = const IconDataDon(0xe64a);
  static const IconData ecard_pay = const IconDataDon(0xe64b);
  static const IconData fire_o = const IconDataDon(0xe64c);
  static const IconData description = const IconDataDon(0xe64d);
  static const IconData credit_pay = const IconDataDon(0xe64e);
  static const IconData filter_o = const IconDataDon(0xe64f);
  static const IconData fire = const IconDataDon(0xe650);
  static const IconData expand_o = const IconDataDon(0xe651);
  static const IconData gem = const IconDataDon(0xe652);
  static const IconData free_postage = const IconDataDon(0xe653);
  static const IconData diamond = const IconDataDon(0xe654);
  static const IconData delete = const IconDataDon(0xe655);
  static const IconData gift = const IconDataDon(0xe656);
  static const IconData ellipsis = const IconDataDon(0xe657);
  static const IconData friends_o = const IconDataDon(0xe658);
  static const IconData gold_coin = const IconDataDon(0xe659);
  static const IconData gift_card = const IconDataDon(0xe65a);
  static const IconData gold_coin_o = const IconDataDon(0xe65b);
  static const IconData expand = const IconDataDon(0xe65c);
  static const IconData hotel_o = const IconDataDon(0xe65d);
  static const IconData info_o = const IconDataDon(0xe65e);
  static const IconData graphic = const IconDataDon(0xe65f);
  static const IconData hot = const IconDataDon(0xe660);
  static const IconData gift_o = const IconDataDon(0xe661);
  static const IconData discount = const IconDataDon(0xe662);
  static const IconData label_o = const IconDataDon(0xe663);
  static const IconData friends = const IconDataDon(0xe664);
  static const IconData hot_o = const IconDataDon(0xe665);
  static const IconData live = const IconDataDon(0xe666);
  static const IconData flower_o = const IconDataDon(0xe667);
  static const IconData info = const IconDataDon(0xe668);
  static const IconData hot_sale = const IconDataDon(0xe669);
  static const IconData manager = const IconDataDon(0xe66a);
  static const IconData idcard = const IconDataDon(0xe66b);
  static const IconData gem_o = const IconDataDon(0xe66c);
  static const IconData manager_o = const IconDataDon(0xe66d);
  static const IconData goods_collect_o = const IconDataDon(0xe66e);
  static const IconData home_o = const IconDataDon(0xe66f);
  static const IconData label = const IconDataDon(0xe670);
  static const IconData medel = const IconDataDon(0xe671);
  static const IconData location_o = const IconDataDon(0xe672);
  static const IconData music_o = const IconDataDon(0xe673);
  static const IconData new_arrival_o = const IconDataDon(0xe674);
  static const IconData logistics = const IconDataDon(0xe675);
  static const IconData new_o = const IconDataDon(0xe676);
  static const IconData invition = const IconDataDon(0xe677);
  static const IconData more_o = const IconDataDon(0xe678);
  static const IconData other_pay = const IconDataDon(0xe679);
  static const IconData new_arrival = const IconDataDon(0xe67a);
  static const IconData location = const IconDataDon(0xe67b);
  static const IconData pause_circle_o = const IconDataDon(0xe67c);
  static const IconData gift_card_o = const IconDataDon(0xe67d);
  static const IconData like = const IconDataDon(0xe67e);
  static const IconData paid = const IconDataDon(0xe67f);
  static const IconData notes_o = const IconDataDon(0xe680);
  static const IconData map_marked = const IconDataDon(0xe681);
  static const IconData newspaper_o = const IconDataDon(0xe682);
  static const IconData more = const IconDataDon(0xe683);
  static const IconData photo = const IconDataDon(0xe684);
  static const IconData peer_pay = const IconDataDon(0xe685);
  static const IconData pause_circle = const IconDataDon(0xe686);
  static const IconData pause = const IconDataDon(0xe687);
  static const IconData orders_o = const IconDataDon(0xe688);
  static const IconData new_fill = const IconDataDon(0xe689);
  static const IconData like_o = const IconDataDon(0xe68a);
  static const IconData phone_o = const IconDataDon(0xe68b);
  static const IconData phone = const IconDataDon(0xe68c);
  static const IconData hot_sale_o = const IconDataDon(0xe68d);
  static const IconData pending_payment = const IconDataDon(0xe68e);
  static const IconData photograph = const IconDataDon(0xe68f);
  static const IconData lock = const IconDataDon(0xe690);
  static const IconData qr_invalid = const IconDataDon(0xe691);
  static const IconData play = const IconDataDon(0xe692);
  static const IconData phone_circle_o = const IconDataDon(0xe693);
  static const IconData passed = const IconDataDon(0xe694);
  static const IconData empty = const IconDataDon(0xe695);
  static const IconData play_circle = const IconDataDon(0xe696);
  static const IconData printer = const IconDataDon(0xe697);
  static const IconData question = const IconDataDon(0xe698);
  static const IconData search = const IconDataDon(0xe699);
  static const IconData play_circle_o = const IconDataDon(0xe69a);
  static const IconData send_gift_o = const IconDataDon(0xe69b);
  static const IconData plus = const IconDataDon(0xe69c);
  static const IconData medel_o = const IconDataDon(0xe69d);
  static const IconData photo_o = const IconDataDon(0xe69e);
  static const IconData point_gift = const IconDataDon(0xe69f);
  static const IconData eye_o = const IconDataDon(0xe6a0);
  static const IconData service = const IconDataDon(0xe6a1);
  static const IconData question_o = const IconDataDon(0xe6a2);
  static const IconData goods_collect = const IconDataDon(0xe6a3);
  static const IconData setting_o = const IconDataDon(0xe6a4);
  static const IconData setting = const IconDataDon(0xe6a5);
  static const IconData refund_o = const IconDataDon(0xe6a6);
  static const IconData records = const IconDataDon(0xe6a7);
  static const IconData shop_collect = const IconDataDon(0xe6a8);
  static const IconData points = const IconDataDon(0xe6a9);
  static const IconData flag_o = const IconDataDon(0xe6aa);
  static const IconData point_gift_o = const IconDataDon(0xe6ab);
  static const IconData star_o = const IconDataDon(0xe6ac);
  static const IconData shop = const IconDataDon(0xe6ad);
  static const IconData sign = const IconDataDon(0xe6ae);
  static const IconData qr = const IconDataDon(0xe6af);
  static const IconData shrink = const IconDataDon(0xe6b0);
  static const IconData stop_circle_o = const IconDataDon(0xe6b1);
  static const IconData smile_o = const IconDataDon(0xe6b2);
  static const IconData tv_o = const IconDataDon(0xe6b3);
  static const IconData scan = const IconDataDon(0xe6b4);
  static const IconData smile_comment_o = const IconDataDon(0xe6b5);
  static const IconData umbrella_circle = const IconDataDon(0xe6b6);
  static const IconData todo_list = const IconDataDon(0xe6b7);
  static const IconData todo_list_o = const IconDataDon(0xe6b8);
  static const IconData underway_o = const IconDataDon(0xe6b9);
  static const IconData shop_o = const IconDataDon(0xe6ba);
  static const IconData shopping_cart_o = const IconDataDon(0xe6bb);
  static const IconData video = const IconDataDon(0xe6bc);
  static const IconData user_o = const IconDataDon(0xe6bd);
  static const IconData share = const IconDataDon(0xe6be);
  static const IconData replay = const IconDataDon(0xe6bf);
  static const IconData vip_card = const IconDataDon(0xe6c0);
  static const IconData volume_o = const IconDataDon(0xe6c1);
  static const IconData warning_o = const IconDataDon(0xe6c2);
  static const IconData wap_home = const IconDataDon(0xe6c3);
  static const IconData stop_circle = const IconDataDon(0xe6c4);
  static const IconData wechat = const IconDataDon(0xe6c5);
  static const IconData warn_o = const IconDataDon(0xe6c6);
  static const IconData service_o = const IconDataDon(0xe6c7);
  static const IconData tosend = const IconDataDon(0xe6c8);
  static const IconData youzan_shield = const IconDataDon(0xe6c9);
  static const IconData thumb_circle_o = const IconDataDon(0xe6ca);
  static const IconData smile_comment = const IconDataDon(0xe6cb);
  static const IconData volume = const IconDataDon(0xe6cc);
  static const IconData video_o = const IconDataDon(0xe6cd);
  static const IconData vip_card_o = const IconDataDon(0xe6ce);
  static const IconData underway = const IconDataDon(0xe6cf);
  static const IconData user_circle_o = const IconDataDon(0xe6d0);
  static const IconData wap_nav = const IconDataDon(0xe6d1);
  static const IconData weapp_nav = const IconDataDon(0xe6d2);
  static const IconData shopping_cart = const IconDataDon(0xe6d3);
  static const IconData success = const IconDataDon(0xe6d4);
  static const IconData send_gift = const IconDataDon(0xe6d5);
  static const IconData upgrade = const IconDataDon(0xe6d6);
  static const IconData shop_collect_o = const IconDataDon(0xe6d7);
  static const IconData star = const IconDataDon(0xe6d8);
  static const IconData stop = const IconDataDon(0xe6d9);
  static const IconData add = const IconDataDon(0xe600);
  static const IconData add_o = const IconDataDon(0xe601);
  static const IconData aim = const IconDataDon(0xe602);
  static const IconData add_square = const IconDataDon(0xe603);
  static const IconData arrow = const IconDataDon(0xe604);
  static const IconData arrow_up = const IconDataDon(0xe605);
  static const IconData apps_o = const IconDataDon(0xe606);
  static const IconData ascending = const IconDataDon(0xe607);
  static const IconData award = const IconDataDon(0xe608);
  static const IconData arrow_down = const IconDataDon(0xe609);
  static const IconData arrow_left = const IconDataDon(0xe60a);
  static const IconData bag = const IconDataDon(0xe60b);
  static const IconData audio = const IconDataDon(0xe60c);
  static const IconData balance_list = const IconDataDon(0xe60d);
  static const IconData balance_list_o = const IconDataDon(0xe60e);
  static const IconData award_o = const IconDataDon(0xe60f);
  static const IconData bag_o = const IconDataDon(0xe610);
  static const IconData bill = const IconDataDon(0xe611);
  static const IconData bookmark = const IconDataDon(0xe612);
  static const IconData balance_o = const IconDataDon(0xe613);
  static const IconData after_sale = const IconDataDon(0xe614);
  static const IconData bars = const IconDataDon(0xe615);
  static const IconData bell = const IconDataDon(0xe616);
  static const IconData bookmark_o = const IconDataDon(0xe617);
  static const IconData bar_chart_o = const IconDataDon(0xe618);
  static const IconData bill_o = const IconDataDon(0xe619);
  static const IconData bullhorn_o = const IconDataDon(0xe61a);
  static const IconData cart = const IconDataDon(0xe61b);
  static const IconData browsing_history_o = const IconDataDon(0xe61c);
  static const IconData brush_o = const IconDataDon(0xe61d);
  static const IconData alipay = const IconDataDon(0xe61e);
  static const IconData balance_pay = const IconDataDon(0xe61f);
}

const Map<String, IconData> DonIconsMap = <String, IconData>{
  'loading1': DonIcons.loading1,
  'loading5': DonIcons.loading5,
  'loading2': DonIcons.loading2,
  'sync': DonIcons.sync,
  'loading': DonIcons.loading,
  'loading3': DonIcons.loading3,
  'loading4': DonIcons.loading4,
  'birthday_cake_o': DonIcons.birthday_cake_o,
  'calender_o': DonIcons.calender_o,
  'cash_on_deliver': DonIcons.cash_on_deliver,
  'chat': DonIcons.chat,
  'cart_o': DonIcons.cart_o,
  'cart_circle_o': DonIcons.cart_circle_o,
  'chat_o': DonIcons.chat_o,
  'cart_circle': DonIcons.cart_circle,
  'clock_o': DonIcons.clock_o,
  'certificate': DonIcons.certificate,
  'bulb_o': DonIcons.bulb_o,
  'cluster': DonIcons.cluster,
  'clear': DonIcons.clear,
  'card': DonIcons.card,
  'column': DonIcons.column,
  'circle': DonIcons.circle,
  'browsing_history': DonIcons.browsing_history,
  'close': DonIcons.close,
  'cluster_o': DonIcons.cluster_o,
  'cash_back_record': DonIcons.cash_back_record,
  'checked': DonIcons.checked,
  'comment_o': DonIcons.comment_o,
  'completed': DonIcons.completed,
  'coupon_o': DonIcons.coupon_o,
  'clock': DonIcons.clock,
  'comment_circle_o': DonIcons.comment_circle_o,
  'cashier_o': DonIcons.cashier_o,
  'contact': DonIcons.contact,
  'comment': DonIcons.comment,
  'desktop_o': DonIcons.desktop_o,
  'debit_pay': DonIcons.debit_pay,
  'diamond_o': DonIcons.diamond_o,
  'chart_trending_o': DonIcons.chart_trending_o,
  'exchange': DonIcons.exchange,
  'failure': DonIcons.failure,
  'closed_eye': DonIcons.closed_eye,
  'cross': DonIcons.cross,
  'coupon': DonIcons.coupon,
  'edit': DonIcons.edit,
  'fail': DonIcons.fail,
  'envelop_o': DonIcons.envelop_o,
  'descending': DonIcons.descending,
  'eye': DonIcons.eye,
  'ecard_pay': DonIcons.ecard_pay,
  'fire_o': DonIcons.fire_o,
  'description': DonIcons.description,
  'credit_pay': DonIcons.credit_pay,
  'filter_o': DonIcons.filter_o,
  'fire': DonIcons.fire,
  'expand_o': DonIcons.expand_o,
  'gem': DonIcons.gem,
  'free_postage': DonIcons.free_postage,
  'diamond': DonIcons.diamond,
  'delete': DonIcons.delete,
  'gift': DonIcons.gift,
  'ellipsis': DonIcons.ellipsis,
  'friends_o': DonIcons.friends_o,
  'gold_coin': DonIcons.gold_coin,
  'gift_card': DonIcons.gift_card,
  'gold_coin_o': DonIcons.gold_coin_o,
  'expand': DonIcons.expand,
  'hotel_o': DonIcons.hotel_o,
  'info_o': DonIcons.info_o,
  'graphic': DonIcons.graphic,
  'hot': DonIcons.hot,
  'gift_o': DonIcons.gift_o,
  'discount': DonIcons.discount,
  'label_o': DonIcons.label_o,
  'friends': DonIcons.friends,
  'hot_o': DonIcons.hot_o,
  'live': DonIcons.live,
  'flower_o': DonIcons.flower_o,
  'info': DonIcons.info,
  'hot_sale': DonIcons.hot_sale,
  'manager': DonIcons.manager,
  'idcard': DonIcons.idcard,
  'gem_o': DonIcons.gem_o,
  'manager_o': DonIcons.manager_o,
  'goods_collect_o': DonIcons.goods_collect_o,
  'home_o': DonIcons.home_o,
  'label': DonIcons.label,
  'medel': DonIcons.medel,
  'location_o': DonIcons.location_o,
  'music_o': DonIcons.music_o,
  'new_arrival_o': DonIcons.new_arrival_o,
  'logistics': DonIcons.logistics,
  'new_o': DonIcons.new_o,
  'invition': DonIcons.invition,
  'more_o': DonIcons.more_o,
  'other_pay': DonIcons.other_pay,
  'new_arrival': DonIcons.new_arrival,
  'location': DonIcons.location,
  'pause_circle_o': DonIcons.pause_circle_o,
  'gift_card_o': DonIcons.gift_card_o,
  'like': DonIcons.like,
  'paid': DonIcons.paid,
  'notes_o': DonIcons.notes_o,
  'map_marked': DonIcons.map_marked,
  'newspaper_o': DonIcons.newspaper_o,
  'more': DonIcons.more,
  'photo': DonIcons.photo,
  'peer_pay': DonIcons.peer_pay,
  'pause_circle': DonIcons.pause_circle,
  'pause': DonIcons.pause,
  'orders_o': DonIcons.orders_o,
  'new_fill': DonIcons.new_fill,
  'like_o': DonIcons.like_o,
  'phone_o': DonIcons.phone_o,
  'phone': DonIcons.phone,
  'hot_sale_o': DonIcons.hot_sale_o,
  'pending_payment': DonIcons.pending_payment,
  'photograph': DonIcons.photograph,
  'lock': DonIcons.lock,
  'qr_invalid': DonIcons.qr_invalid,
  'play': DonIcons.play,
  'phone_circle_o': DonIcons.phone_circle_o,
  'passed': DonIcons.passed,
  'empty': DonIcons.empty,
  'play_circle': DonIcons.play_circle,
  'printer': DonIcons.printer,
  'question': DonIcons.question,
  'search': DonIcons.search,
  'play_circle_o': DonIcons.play_circle_o,
  'send_gift_o': DonIcons.send_gift_o,
  'plus': DonIcons.plus,
  'medel_o': DonIcons.medel_o,
  'photo_o': DonIcons.photo_o,
  'point_gift': DonIcons.point_gift,
  'eye_o': DonIcons.eye_o,
  'service': DonIcons.service,
  'question_o': DonIcons.question_o,
  'goods_collect': DonIcons.goods_collect,
  'setting_o': DonIcons.setting_o,
  'setting': DonIcons.setting,
  'refund_o': DonIcons.refund_o,
  'records': DonIcons.records,
  'shop_collect': DonIcons.shop_collect,
  'points': DonIcons.points,
  'flag_o': DonIcons.flag_o,
  'point_gift_o': DonIcons.point_gift_o,
  'star_o': DonIcons.star_o,
  'shop': DonIcons.shop,
  'sign': DonIcons.sign,
  'qr': DonIcons.qr,
  'shrink': DonIcons.shrink,
  'stop_circle_o': DonIcons.stop_circle_o,
  'smile_o': DonIcons.smile_o,
  'tv_o': DonIcons.tv_o,
  'scan': DonIcons.scan,
  'smile_comment_o': DonIcons.smile_comment_o,
  'umbrella_circle': DonIcons.umbrella_circle,
  'todo_list': DonIcons.todo_list,
  'todo_list_o': DonIcons.todo_list_o,
  'underway_o': DonIcons.underway_o,
  'shop_o': DonIcons.shop_o,
  'shopping_cart_o': DonIcons.shopping_cart_o,
  'video': DonIcons.video,
  'user_o': DonIcons.user_o,
  'share': DonIcons.share,
  'replay': DonIcons.replay,
  'vip_card': DonIcons.vip_card,
  'volume_o': DonIcons.volume_o,
  'warning_o': DonIcons.warning_o,
  'wap_home': DonIcons.wap_home,
  'stop_circle': DonIcons.stop_circle,
  'wechat': DonIcons.wechat,
  'warn_o': DonIcons.warn_o,
  'service_o': DonIcons.service_o,
  'tosend': DonIcons.tosend,
  'youzan_shield': DonIcons.youzan_shield,
  'thumb_circle_o': DonIcons.thumb_circle_o,
  'smile_comment': DonIcons.smile_comment,
  'volume': DonIcons.volume,
  'video_o': DonIcons.video_o,
  'vip_card_o': DonIcons.vip_card_o,
  'underway': DonIcons.underway,
  'user_circle_o': DonIcons.user_circle_o,
  'wap_nav': DonIcons.wap_nav,
  'weapp_nav': DonIcons.weapp_nav,
  'shopping_cart': DonIcons.shopping_cart,
  'success': DonIcons.success,
  'send_gift': DonIcons.send_gift,
  'upgrade': DonIcons.upgrade,
  'shop_collect_o': DonIcons.shop_collect_o,
  'star': DonIcons.star,
  'stop': DonIcons.stop,
  'add': DonIcons.add,
  'add_o': DonIcons.add_o,
  'aim': DonIcons.aim,
  'add_square': DonIcons.add_square,
  'arrow': DonIcons.arrow,
  'arrow_up': DonIcons.arrow_up,
  'apps_o': DonIcons.apps_o,
  'ascending': DonIcons.ascending,
  'award': DonIcons.award,
  'arrow_down': DonIcons.arrow_down,
  'arrow_left': DonIcons.arrow_left,
  'bag': DonIcons.bag,
  'audio': DonIcons.audio,
  'balance_list': DonIcons.balance_list,
  'balance_list_o': DonIcons.balance_list_o,
  'award_o': DonIcons.award_o,
  'bag_o': DonIcons.bag_o,
  'bill': DonIcons.bill,
  'bookmark': DonIcons.bookmark,
  'balance_o': DonIcons.balance_o,
  'after_sale': DonIcons.after_sale,
  'bars': DonIcons.bars,
  'bell': DonIcons.bell,
  'bookmark_o': DonIcons.bookmark_o,
  'bar_chart_o': DonIcons.bar_chart_o,
  'bill_o': DonIcons.bill_o,
  'bullhorn_o': DonIcons.bullhorn_o,
  'cart': DonIcons.cart,
  'browsing_history_o': DonIcons.browsing_history_o,
  'brush_o': DonIcons.brush_o,
  'alipay': DonIcons.alipay,
  'balance_pay': DonIcons.balance_pay,
};
