library don_icons;

import 'package:flutter/widgets.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!

class DonIcons {
  static const IconData birthdayCakeO =
      const IconData(0xe620, fontFamily: 'Iconfont');
  static const IconData calenderO =
      const IconData(0xe621, fontFamily: 'Iconfont');
  static const IconData cashOnDeliver =
      const IconData(0xe622, fontFamily: 'Iconfont');
  static const IconData chat = const IconData(0xe623, fontFamily: 'Iconfont');
  static const IconData cartO = const IconData(0xe624, fontFamily: 'Iconfont');
  static const IconData cartCircleO =
      const IconData(0xe625, fontFamily: 'Iconfont');
  static const IconData chatO = const IconData(0xe626, fontFamily: 'Iconfont');
  static const IconData cartCircle =
      const IconData(0xe627, fontFamily: 'Iconfont');
  static const IconData clockO = const IconData(0xe628, fontFamily: 'Iconfont');
  static const IconData certificate =
      const IconData(0xe629, fontFamily: 'Iconfont');
  static const IconData bulbO = const IconData(0xe62a, fontFamily: 'Iconfont');
  static const IconData cluster =
      const IconData(0xe62b, fontFamily: 'Iconfont');
  static const IconData clear = const IconData(0xe62c, fontFamily: 'Iconfont');
  static const IconData card = const IconData(0xe62d, fontFamily: 'Iconfont');
  static const IconData column = const IconData(0xe62e, fontFamily: 'Iconfont');
  static const IconData circle = const IconData(0xe62f, fontFamily: 'Iconfont');
  static const IconData browsingHistory =
      const IconData(0xe630, fontFamily: 'Iconfont');
  static const IconData close = const IconData(0xe631, fontFamily: 'Iconfont');
  static const IconData clusterO =
      const IconData(0xe632, fontFamily: 'Iconfont');
  static const IconData cashBackRecord =
      const IconData(0xe633, fontFamily: 'Iconfont');
  static const IconData checked =
      const IconData(0xe634, fontFamily: 'Iconfont');
  static const IconData commentO =
      const IconData(0xe635, fontFamily: 'Iconfont');
  static const IconData completed =
      const IconData(0xe636, fontFamily: 'Iconfont');
  static const IconData couponO =
      const IconData(0xe637, fontFamily: 'Iconfont');
  static const IconData clock = const IconData(0xe638, fontFamily: 'Iconfont');
  static const IconData commentCircleO =
      const IconData(0xe639, fontFamily: 'Iconfont');
  static const IconData cashierO =
      const IconData(0xe63a, fontFamily: 'Iconfont');
  static const IconData contact =
      const IconData(0xe63b, fontFamily: 'Iconfont');
  static const IconData comment =
      const IconData(0xe63c, fontFamily: 'Iconfont');
  static const IconData desktopO =
      const IconData(0xe63d, fontFamily: 'Iconfont');
  static const IconData debitPay =
      const IconData(0xe63e, fontFamily: 'Iconfont');
  static const IconData diamondO =
      const IconData(0xe63f, fontFamily: 'Iconfont');
  static const IconData chartTrendingO =
      const IconData(0xe640, fontFamily: 'Iconfont');
  static const IconData exchange =
      const IconData(0xe641, fontFamily: 'Iconfont');
  static const IconData failure =
      const IconData(0xe642, fontFamily: 'Iconfont');
  static const IconData closedEye =
      const IconData(0xe643, fontFamily: 'Iconfont');
  static const IconData cross = const IconData(0xe644, fontFamily: 'Iconfont');
  static const IconData coupon = const IconData(0xe645, fontFamily: 'Iconfont');
  static const IconData edit = const IconData(0xe646, fontFamily: 'Iconfont');
  static const IconData fail = const IconData(0xe647, fontFamily: 'Iconfont');
  static const IconData envelopO =
      const IconData(0xe648, fontFamily: 'Iconfont');
  static const IconData descending =
      const IconData(0xe649, fontFamily: 'Iconfont');
  static const IconData eye = const IconData(0xe64a, fontFamily: 'Iconfont');
  static const IconData ecardPay =
      const IconData(0xe64b, fontFamily: 'Iconfont');
  static const IconData fireO = const IconData(0xe64c, fontFamily: 'Iconfont');
  static const IconData description =
      const IconData(0xe64d, fontFamily: 'Iconfont');
  static const IconData creditPay =
      const IconData(0xe64e, fontFamily: 'Iconfont');
  static const IconData filterO =
      const IconData(0xe64f, fontFamily: 'Iconfont');
  static const IconData fire = const IconData(0xe650, fontFamily: 'Iconfont');
  static const IconData expandO =
      const IconData(0xe651, fontFamily: 'Iconfont');
  static const IconData gem = const IconData(0xe652, fontFamily: 'Iconfont');
  static const IconData freePostage =
      const IconData(0xe653, fontFamily: 'Iconfont');
  static const IconData diamond =
      const IconData(0xe654, fontFamily: 'Iconfont');
  static const IconData delete = const IconData(0xe655, fontFamily: 'Iconfont');
  static const IconData gift = const IconData(0xe656, fontFamily: 'Iconfont');
  static const IconData ellipsis =
      const IconData(0xe657, fontFamily: 'Iconfont');
  static const IconData friendsO =
      const IconData(0xe658, fontFamily: 'Iconfont');
  static const IconData goldCoin =
      const IconData(0xe659, fontFamily: 'Iconfont');
  static const IconData giftCard =
      const IconData(0xe65a, fontFamily: 'Iconfont');
  static const IconData goldCoinO =
      const IconData(0xe65b, fontFamily: 'Iconfont');
  static const IconData expand = const IconData(0xe65c, fontFamily: 'Iconfont');
  static const IconData hotelO = const IconData(0xe65d, fontFamily: 'Iconfont');
  static const IconData infoO = const IconData(0xe65e, fontFamily: 'Iconfont');
  static const IconData graphic =
      const IconData(0xe65f, fontFamily: 'Iconfont');
  static const IconData hot = const IconData(0xe660, fontFamily: 'Iconfont');
  static const IconData giftO = const IconData(0xe661, fontFamily: 'Iconfont');
  static const IconData discount =
      const IconData(0xe662, fontFamily: 'Iconfont');
  static const IconData labelO = const IconData(0xe663, fontFamily: 'Iconfont');
  static const IconData friends =
      const IconData(0xe664, fontFamily: 'Iconfont');
  static const IconData hotO = const IconData(0xe665, fontFamily: 'Iconfont');
  static const IconData live = const IconData(0xe666, fontFamily: 'Iconfont');
  static const IconData flowerO =
      const IconData(0xe667, fontFamily: 'Iconfont');
  static const IconData info = const IconData(0xe668, fontFamily: 'Iconfont');
  static const IconData hotSale =
      const IconData(0xe669, fontFamily: 'Iconfont');
  static const IconData manager =
      const IconData(0xe66a, fontFamily: 'Iconfont');
  static const IconData idcard = const IconData(0xe66b, fontFamily: 'Iconfont');
  static const IconData gemO = const IconData(0xe66c, fontFamily: 'Iconfont');
  static const IconData managerO =
      const IconData(0xe66d, fontFamily: 'Iconfont');
  static const IconData goodsCollectO =
      const IconData(0xe66e, fontFamily: 'Iconfont');
  static const IconData homeO = const IconData(0xe66f, fontFamily: 'Iconfont');
  static const IconData label = const IconData(0xe670, fontFamily: 'Iconfont');
  static const IconData medel = const IconData(0xe671, fontFamily: 'Iconfont');
  static const IconData locationO =
      const IconData(0xe672, fontFamily: 'Iconfont');
  static const IconData musicO = const IconData(0xe673, fontFamily: 'Iconfont');
  static const IconData newArrivalO =
      const IconData(0xe674, fontFamily: 'Iconfont');
  static const IconData logistics =
      const IconData(0xe675, fontFamily: 'Iconfont');
  static const IconData newO = const IconData(0xe676, fontFamily: 'Iconfont');
  static const IconData invition =
      const IconData(0xe677, fontFamily: 'Iconfont');
  static const IconData moreO = const IconData(0xe678, fontFamily: 'Iconfont');
  static const IconData otherPay =
      const IconData(0xe679, fontFamily: 'Iconfont');
  static const IconData newArrival =
      const IconData(0xe67a, fontFamily: 'Iconfont');
  static const IconData location =
      const IconData(0xe67b, fontFamily: 'Iconfont');
  static const IconData pauseCircleO =
      const IconData(0xe67c, fontFamily: 'Iconfont');
  static const IconData giftCardO =
      const IconData(0xe67d, fontFamily: 'Iconfont');
  static const IconData like = const IconData(0xe67e, fontFamily: 'Iconfont');
  static const IconData paid = const IconData(0xe67f, fontFamily: 'Iconfont');
  static const IconData notesO = const IconData(0xe680, fontFamily: 'Iconfont');
  static const IconData mapMarked =
      const IconData(0xe681, fontFamily: 'Iconfont');
  static const IconData newspaperO =
      const IconData(0xe682, fontFamily: 'Iconfont');
  static const IconData more = const IconData(0xe683, fontFamily: 'Iconfont');
  static const IconData photo = const IconData(0xe684, fontFamily: 'Iconfont');
  static const IconData peerPay =
      const IconData(0xe685, fontFamily: 'Iconfont');
  static const IconData pauseCircle =
      const IconData(0xe686, fontFamily: 'Iconfont');
  static const IconData pause = const IconData(0xe687, fontFamily: 'Iconfont');
  static const IconData ordersO =
      const IconData(0xe688, fontFamily: 'Iconfont');
  static const IconData newFill =
      const IconData(0xe689, fontFamily: 'Iconfont');
  static const IconData likeO = const IconData(0xe68a, fontFamily: 'Iconfont');
  static const IconData phoneO = const IconData(0xe68b, fontFamily: 'Iconfont');
  static const IconData phone = const IconData(0xe68c, fontFamily: 'Iconfont');
  static const IconData hotSaleO =
      const IconData(0xe68d, fontFamily: 'Iconfont');
  static const IconData pendingPayment =
      const IconData(0xe68e, fontFamily: 'Iconfont');
  static const IconData photograph =
      const IconData(0xe68f, fontFamily: 'Iconfont');
  static const IconData lock = const IconData(0xe690, fontFamily: 'Iconfont');
  static const IconData qrInvalid =
      const IconData(0xe691, fontFamily: 'Iconfont');
  static const IconData play = const IconData(0xe692, fontFamily: 'Iconfont');
  static const IconData phoneCircleO =
      const IconData(0xe693, fontFamily: 'Iconfont');
  static const IconData passed = const IconData(0xe694, fontFamily: 'Iconfont');
  static const IconData empty = const IconData(0xe695, fontFamily: 'Iconfont');
  static const IconData playCircle =
      const IconData(0xe696, fontFamily: 'Iconfont');
  static const IconData printer =
      const IconData(0xe697, fontFamily: 'Iconfont');
  static const IconData question =
      const IconData(0xe698, fontFamily: 'Iconfont');
  static const IconData search = const IconData(0xe699, fontFamily: 'Iconfont');
  static const IconData playCircleO =
      const IconData(0xe69a, fontFamily: 'Iconfont');
  static const IconData sendGiftO =
      const IconData(0xe69b, fontFamily: 'Iconfont');
  static const IconData plus = const IconData(0xe69c, fontFamily: 'Iconfont');
  static const IconData medelO = const IconData(0xe69d, fontFamily: 'Iconfont');
  static const IconData photoO = const IconData(0xe69e, fontFamily: 'Iconfont');
  static const IconData pointGift =
      const IconData(0xe69f, fontFamily: 'Iconfont');
  static const IconData eyeO = const IconData(0xe6a0, fontFamily: 'Iconfont');
  static const IconData service =
      const IconData(0xe6a1, fontFamily: 'Iconfont');
  static const IconData questionO =
      const IconData(0xe6a2, fontFamily: 'Iconfont');
  static const IconData goodsCollect =
      const IconData(0xe6a3, fontFamily: 'Iconfont');
  static const IconData settingO =
      const IconData(0xe6a4, fontFamily: 'Iconfont');
  static const IconData setting =
      const IconData(0xe6a5, fontFamily: 'Iconfont');
  static const IconData refundO =
      const IconData(0xe6a6, fontFamily: 'Iconfont');
  static const IconData records =
      const IconData(0xe6a7, fontFamily: 'Iconfont');
  static const IconData shopCollect =
      const IconData(0xe6a8, fontFamily: 'Iconfont');
  static const IconData points = const IconData(0xe6a9, fontFamily: 'Iconfont');
  static const IconData flagO = const IconData(0xe6aa, fontFamily: 'Iconfont');
  static const IconData pointGiftO =
      const IconData(0xe6ab, fontFamily: 'Iconfont');
  static const IconData starO = const IconData(0xe6ac, fontFamily: 'Iconfont');
  static const IconData shop = const IconData(0xe6ad, fontFamily: 'Iconfont');
  static const IconData sign = const IconData(0xe6ae, fontFamily: 'Iconfont');
  static const IconData qr = const IconData(0xe6af, fontFamily: 'Iconfont');
  static const IconData shrink = const IconData(0xe6b0, fontFamily: 'Iconfont');
  static const IconData stopCircleO =
      const IconData(0xe6b1, fontFamily: 'Iconfont');
  static const IconData smileO = const IconData(0xe6b2, fontFamily: 'Iconfont');
  static const IconData tvO = const IconData(0xe6b3, fontFamily: 'Iconfont');
  static const IconData scan = const IconData(0xe6b4, fontFamily: 'Iconfont');
  static const IconData smileCommentO =
      const IconData(0xe6b5, fontFamily: 'Iconfont');
  static const IconData umbrellaCircle =
      const IconData(0xe6b6, fontFamily: 'Iconfont');
  static const IconData todoList =
      const IconData(0xe6b7, fontFamily: 'Iconfont');
  static const IconData todoListO =
      const IconData(0xe6b8, fontFamily: 'Iconfont');
  static const IconData underwayO =
      const IconData(0xe6b9, fontFamily: 'Iconfont');
  static const IconData shopO = const IconData(0xe6ba, fontFamily: 'Iconfont');
  static const IconData shoppingCartO =
      const IconData(0xe6bb, fontFamily: 'Iconfont');
  static const IconData video = const IconData(0xe6bc, fontFamily: 'Iconfont');
  static const IconData userO = const IconData(0xe6bd, fontFamily: 'Iconfont');
  static const IconData share = const IconData(0xe6be, fontFamily: 'Iconfont');
  static const IconData replay = const IconData(0xe6bf, fontFamily: 'Iconfont');
  static const IconData vipCard =
      const IconData(0xe6c0, fontFamily: 'Iconfont');
  static const IconData volumeO =
      const IconData(0xe6c1, fontFamily: 'Iconfont');
  static const IconData warningO =
      const IconData(0xe6c2, fontFamily: 'Iconfont');
  static const IconData wapHome =
      const IconData(0xe6c3, fontFamily: 'Iconfont');
  static const IconData stopCircle =
      const IconData(0xe6c4, fontFamily: 'Iconfont');
  static const IconData wechat = const IconData(0xe6c5, fontFamily: 'Iconfont');
  static const IconData warnO = const IconData(0xe6c6, fontFamily: 'Iconfont');
  static const IconData serviceO =
      const IconData(0xe6c7, fontFamily: 'Iconfont');
  static const IconData tosend = const IconData(0xe6c8, fontFamily: 'Iconfont');
  static const IconData youzanShield =
      const IconData(0xe6c9, fontFamily: 'Iconfont');
  static const IconData thumbCircleO =
      const IconData(0xe6ca, fontFamily: 'Iconfont');
  static const IconData smileComment =
      const IconData(0xe6cb, fontFamily: 'Iconfont');
  static const IconData volume = const IconData(0xe6cc, fontFamily: 'Iconfont');
  static const IconData videoO = const IconData(0xe6cd, fontFamily: 'Iconfont');
  static const IconData vipCardO =
      const IconData(0xe6ce, fontFamily: 'Iconfont');
  static const IconData underway =
      const IconData(0xe6cf, fontFamily: 'Iconfont');
  static const IconData userCircleO =
      const IconData(0xe6d0, fontFamily: 'Iconfont');
  static const IconData wapNav = const IconData(0xe6d1, fontFamily: 'Iconfont');
  static const IconData weappNav =
      const IconData(0xe6d2, fontFamily: 'Iconfont');
  static const IconData shoppingCart =
      const IconData(0xe6d3, fontFamily: 'Iconfont');
  static const IconData success =
      const IconData(0xe6d4, fontFamily: 'Iconfont');
  static const IconData sendGift =
      const IconData(0xe6d5, fontFamily: 'Iconfont');
  static const IconData upgrade =
      const IconData(0xe6d6, fontFamily: 'Iconfont');
  static const IconData shopCollectO =
      const IconData(0xe6d7, fontFamily: 'Iconfont');
  static const IconData star = const IconData(0xe6d8, fontFamily: 'Iconfont');
  static const IconData stop = const IconData(0xe6d9, fontFamily: 'Iconfont');
  static const IconData add = const IconData(0xe600, fontFamily: 'Iconfont');
  static const IconData addO = const IconData(0xe601, fontFamily: 'Iconfont');
  static const IconData aim = const IconData(0xe602, fontFamily: 'Iconfont');
  static const IconData addSquare =
      const IconData(0xe603, fontFamily: 'Iconfont');
  static const IconData arrow = const IconData(0xe604, fontFamily: 'Iconfont');
  static const IconData arrowUp =
      const IconData(0xe605, fontFamily: 'Iconfont');
  static const IconData appsO = const IconData(0xe606, fontFamily: 'Iconfont');
  static const IconData ascending =
      const IconData(0xe607, fontFamily: 'Iconfont');
  static const IconData award = const IconData(0xe608, fontFamily: 'Iconfont');
  static const IconData arrowDown =
      const IconData(0xe609, fontFamily: 'Iconfont');
  static const IconData arrowLeft =
      const IconData(0xe60a, fontFamily: 'Iconfont');
  static const IconData bag = const IconData(0xe60b, fontFamily: 'Iconfont');
  static const IconData audio = const IconData(0xe60c, fontFamily: 'Iconfont');
  static const IconData balanceList =
      const IconData(0xe60d, fontFamily: 'Iconfont');
  static const IconData balanceListO =
      const IconData(0xe60e, fontFamily: 'Iconfont');
  static const IconData awardO = const IconData(0xe60f, fontFamily: 'Iconfont');
  static const IconData bagO = const IconData(0xe610, fontFamily: 'Iconfont');
  static const IconData bill = const IconData(0xe611, fontFamily: 'Iconfont');
  static const IconData bookmark =
      const IconData(0xe612, fontFamily: 'Iconfont');
  static const IconData balanceO =
      const IconData(0xe613, fontFamily: 'Iconfont');
  static const IconData afterSale =
      const IconData(0xe614, fontFamily: 'Iconfont');
  static const IconData bars = const IconData(0xe615, fontFamily: 'Iconfont');
  static const IconData bell = const IconData(0xe616, fontFamily: 'Iconfont');
  static const IconData bookmarkO =
      const IconData(0xe617, fontFamily: 'Iconfont');
  static const IconData barChartO =
      const IconData(0xe618, fontFamily: 'Iconfont');
  static const IconData billO = const IconData(0xe619, fontFamily: 'Iconfont');
  static const IconData bullhornO =
      const IconData(0xe61a, fontFamily: 'Iconfont');
  static const IconData cart = const IconData(0xe61b, fontFamily: 'Iconfont');
  static const IconData browsingHistoryO =
      const IconData(0xe61c, fontFamily: 'Iconfont');
  static const IconData brushO = const IconData(0xe61d, fontFamily: 'Iconfont');
  static const IconData alipay = const IconData(0xe61e, fontFamily: 'Iconfont');
  static const IconData balancePay =
      const IconData(0xe61f, fontFamily: 'Iconfont');
}
